version: '3.8'
  services:
    maven:
      build:
        dockerfile: ./mvn/docker_mvn
      volumes:
        - ./app:/webapps

    tomcat:
      build:
        dockerfile: ./mvn/docker_tom
        ports:
          - "8888:8080"
      volumes:
        - ./app:/usr/local/tomcat/webapps

