FROM ubuntu:16.04
RUN apt update && apt install default-jdk git maven -y && mkdir /webapps
RUN git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello.git /opt/git/boxfuse-sample-java-war-hello/
RUN mvn clean package -f /opt/git/boxfuse-sample-java-war-hello/pom.xml
RUN cp /opt/git/boxfuse-sample-java-war-hello/target/*.war  /webapps/test.war