FROM ubuntu:latest
RUN apt update && apt install git maven -y
RUN git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello.git /opt/git/boxfuse-sample-java-war-hello/
RUN mvn clean package -f /opt/git/boxfuse-sample-java-war-hello/pom.xml
RUN cp /opt/git/boxfuse-sample-java-war-hello/target/*.war  /webapps/test.war